spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:postgres}}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123}
    hikari:
      connection-timeout: ${HIKARI_TIMEOUT:20000}
      maximum-pool-size: ${HIKARI_POOL_SIZE:5}
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true